namespace c45 {
extern "C" {
#include "getnames.c"
#include "getdata.c"
#include "trees.c"
#include "getopt.c"
#include "header.c"
#include "average.c"
#include "besttree.c"
#include "build.c"
#include "buildex.i"
#include "c4.5.c"
#include "c4.5rules.c"
#include "classify.c"
#include "confmat.c"
#include "consult.c"
#include "consultr.c"
#include "contin.c"
#include "defns.i"
#include "discr.c"
#include "extern.i"
#include "genlogs.c"
#include "genrules.c"
#include "info.c"
#include "makerules.c"
#include "prune.c"
#include "prunerule.c"
#include "rules.c"
#include "rulex.i"
#include "siftrules.c"
#include "sort.c"
#include "stats.c"
#include "st-thresh.c"
#include "subset.c"
#include "testrules.c"
#include "types.i"
#include "userint.c"
#include "xval-prep.c"
}
}
